# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/core/clip_vector_size_calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<mediapipe/calculators/core/clip_vector_size_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\x95\x01\n\x1f\x43lipVectorSizeCalculatorOptions\x12\x17\n\x0cmax_vec_size\x18\x01 \x01(\x05:\x01\x31\x32Y\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xb6\xea\xfc\x82\x01 \x01(\x0b\x32*.mediapipe.ClipVectorSizeCalculatorOptions')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe.calculators.core.clip_vector_size_calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_CLIPVECTORSIZECALCULATOROPTIONS.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _globals['_CLIPVECTORSIZECALCULATOROPTIONS']._serialized_start=114
  _globals['_CLIPVECTORSIZECALCULATOROPTIONS']._serialized_end=263
# @@protoc_insertion_point(module_scope)
