# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/tasks/cc/components/processors/proto/transformer_params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGmediapipe/tasks/cc/components/processors/proto/transformer_params.proto\x12+mediapipe.tasks.components.processors.proto\"\x80\x03\n\x15TransformerParameters\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x16\n\x0emax_seq_length\x18\x02 \x01(\x05\x12\x15\n\rembedding_dim\x18\x03 \x01(\x05\x12\x18\n\x10hidden_dimension\x18\x04 \x01(\x05\x12\x16\n\x0ehead_dimension\x18\x05 \x01(\x05\x12\x11\n\tnum_heads\x18\x06 \x01(\x05\x12\x12\n\nnum_stacks\x18\x07 \x01(\x05\x12\x14\n\x0cnum_kv_heads\x18\t \x01(\x05\x12q\n\x13\x61ttention_mask_type\x18\n \x01(\x0e\x32T.mediapipe.tasks.components.processors.proto.TransformerParameters.AttentionMaskType\"<\n\x11\x41ttentionMaskType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06\x43\x41USAL\x10\x01\x12\n\n\x06PREFIX\x10\x02J\x04\x08\x08\x10\tBT\n6com.google.mediapipe.tasks.components.processors.protoB\x1aTransformerParametersProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe.tasks.cc.components.processors.proto.transformer_params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n6com.google.mediapipe.tasks.components.processors.protoB\032TransformerParametersProto'
  _globals['_TRANSFORMERPARAMETERS']._serialized_start=121
  _globals['_TRANSFORMERPARAMETERS']._serialized_end=505
  _globals['_TRANSFORMERPARAMETERS_ATTENTIONMASKTYPE']._serialized_start=439
  _globals['_TRANSFORMERPARAMETERS_ATTENTIONMASKTYPE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
