# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/tasks/cc/components/processors/proto/llm_params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.tasks.cc.components.processors.proto import transformer_params_pb2 as mediapipe_dot_tasks_dot_cc_dot_components_dot_processors_dot_proto_dot_transformer__params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?mediapipe/tasks/cc/components/processors/proto/llm_params.proto\x12+mediapipe.tasks.components.processors.proto\x1aGmediapipe/tasks/cc/components/processors/proto/transformer_params.proto\"\xcd\x01\n\rLLMParameters\x12\x62\n\x16transformer_parameters\x18\x01 \x01(\x0b\x32\x42.mediapipe.tasks.components.processors.proto.TransformerParameters\x12\x12\n\nvocab_size\x18\x02 \x01(\x05\x12\x18\n\x10\x64isable_kv_cache\x18\x03 \x01(\x08\x12\x16\n\x0estart_token_id\x18\x04 \x01(\x05\x12\x12\n\nstop_token\x18\x05 \x01(\tBL\n6com.google.mediapipe.tasks.components.processors.protoB\x12LLMParametersProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe.tasks.cc.components.processors.proto.llm_params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n6com.google.mediapipe.tasks.components.processors.protoB\022LLMParametersProto'
  _globals['_LLMPARAMETERS']._serialized_start=186
  _globals['_LLMPARAMETERS']._serialized_end=391
# @@protoc_insertion_point(module_scope)
